import type { Site } from "./types";

// Seed data for Harvest Connect. Replace with a real backend / CMS later.
// Coordinates are real locations so the map looks plausible out of the box.
export const sites: Site[] = [
  {
    id: "fb-001",
    name: "Riverside Community Food Bank",
    type: "food-bank",
    address: "1200 River Rd",
    city: "Sacramento",
    state: "CA",
    zip: "95811",
    lat: 38.5816,
    lng: -121.4944,
    phone: "+1-916-555-0142",
    email: "help@riversidefoodbank.org",
    hours: "Mon–Fri 9:00 AM – 4:00 PM",
    description:
      "Emergency food assistance, weekly produce distribution, and SNAP enrollment help.",
    resources: ["Emergency boxes", "Fresh produce", "SNAP sign-up", "Diapers"],
  },
  {
    id: "hs-001",
    name: "Oak Park Urban Harvest Garden",
    type: "harvest",
    address: "3500 McKinley Blvd",
    city: "Sacramento",
    state: "CA",
    zip: "95816",
    lat: 38.5611,
    lng: -121.4693,
    phone: "+1-916-555-0188",
    email: "grow@oakparkgardeners.org",
    hours: "Sat 8:00 AM – 12:00 PM (volunteer hours)",
    description:
      "Pick-your-own community garden. Take what you need, leave what you can.",
    resources: ["Free produce", "Seeds", "Gardening workshops"],
  },
  {
    id: "fb-002",
    name: "Northside Pantry",
    type: "food-bank",
    address: "455 Del Paso Blvd",
    city: "Sacramento",
    state: "CA",
    zip: "95815",
    lat: 38.6065,
    lng: -121.4679,
    phone: "+1-916-555-0211",
    email: "info@northsidepantry.org",
    hours: "Tue / Thu 10:00 AM – 2:00 PM",
    description:
      "Walk-in pantry serving North Sacramento. No ID required, no questions asked.",
    resources: ["Dry goods", "Baby formula", "Hygiene kits"],
  },
  {
    id: "hs-002",
    name: "South Land Park Free Orchard",
    type: "harvest",
    address: "2101 Land Park Dr",
    city: "Sacramento",
    state: "CA",
    zip: "95822",
    lat: 38.5392,
    lng: -121.5103,
    phone: "+1-916-555-0304",
    email: "orchard@southlandpark.org",
    hours: "Daily sunrise – sunset",
    description:
      "Citrus and stone fruit orchard open to the community. Bring a bag, take a bag.",
    resources: ["Citrus", "Stone fruit", "Free compost"],
  },
  {
    id: "fb-003",
    name: "Midtown Hope Kitchen",
    type: "food-bank",
    address: "1801 Capitol Ave",
    city: "Sacramento",
    state: "CA",
    zip: "95811",
    lat: 38.5774,
    lng: -121.4803,
    phone: "+1-916-555-0423",
    email: "kitchen@midtownhope.org",
    hours: "Mon–Sat 11:00 AM – 1:00 PM (hot meals)",
    description:
      "Free hot meals, brown-bag groceries, and case management for housing and benefits.",
    resources: ["Hot meals", "Brown-bag groceries", "Case management"],
  },
  {
    id: "hs-003",
    name: "Del Paso Heights Community Farm",
    type: "harvest",
    address: "780 Del Paso Heights Blvd",
    city: "Sacramento",
    state: "CA",
    zip: "95838",
    lat: 38.6353,
    lng: -121.4276,
    phone: "+1-916-555-0501",
    email: "farm@delpasofarm.org",
    hours: "Wed / Sat 9:00 AM – 1:00 PM",
    description:
      "Quarter-acre teaching farm. Free seedlings in spring, free harvest in summer/fall.",
    resources: ["Seedlings (seasonal)", "Fresh produce", "Farm education"],
  },
  {
    id: "fb-004",
    name: "West Sac Family Resource Center",
    type: "food-bank",
    address: "1271 Starboard Dr",
    city: "West Sacramento",
    state: "CA",
    zip: "95691",
    lat: 38.5805,
    lng: -121.5302,
    phone: "+1-916-555-0612",
    email: "support@westsacfamily.org",
    hours: "Mon–Fri 8:30 AM – 5:00 PM",
    description:
      "Food pantry plus wraparound services: WIC, CalFresh, and family counseling.",
    resources: ["Pantry", "WIC", "CalFresh enrollment", "Counseling"],
  },
  {
    id: "hs-004",
    name: "Tahoe Park Edible Forest",
    type: "harvest",
    address: "5900 59th St",
    city: "Sacramento",
    state: "CA",
    zip: "95824",
    lat: 38.5486,
    lng: -121.4408,
    phone: "+1-916-555-0719",
    email: "forest@tahoepark.org",
    hours: "Daily dawn – dusk",
    description:
      "Public edible forest with fruit trees, herbs, and berries. Take freely, share kindly.",
    resources: ["Fruit trees", "Herbs", "Berries"],
  },
  // ─── Bay Area: Oakland, Alameda, Hayward ─────────────────────────────
  {
    id: "accfb-oakland",
    name: "Alameda County Community Food Bank",
    type: "food-bank",
    address: "7900 Edgewater Drive",
    city: "Oakland",
    state: "CA",
    zip: "94621",
    lat: 37.7477,
    lng: -122.2031,
    phone: "(510) 635-3663",
    email: "donate@accfb.org",
    hours: "Mon–Fri 9:00 AM – 5:00 PM; CalFresh helpline 9:00 AM – 4:00 PM",
    description:
      "The regional food bank serving all of Alameda County, distributing food to a network of partner pantries and directly to residents in need across the Bay Area.",
    resources: [
      "Food distribution",
      "CalFresh (food stamps) enrollment",
      "Emergency food helpline",
      "Partner agency food distribution",
      "Advocacy",
      "Volunteer opportunities",
    ],
  },
  {
    id: "alameda-food-bank",
    name: "Alameda Food Bank",
    type: "food-bank",
    address: "677 W. Ranger Avenue",
    city: "Alameda",
    state: "CA",
    zip: "94501",
    lat: 37.7702,
    lng: -122.306,
    phone: "(510) 523-5850",
    email: "info@alamedafoodbank.org",
    hours:
      "Mon, Tue, Thu, Fri 9:00 AM – 12:00 PM and 1:00 PM – 3:30 PM; Wed 9:00 AM – 12:00 PM and 1:00 PM – 6:30 PM",
    description:
      "Founded in 1977, this nonprofit provides nourishing food to Alameda residents in need in a compassionate and respectful manner, distributing groceries through a choice-based pantry and curbside pickup for those with mobility barriers.",
    resources: [
      "Choice-based food pantry",
      "Curbside pickup (for mobility-limited clients)",
      "Thrift store",
      "Volunteer opportunities",
      "Food donations",
    ],
  },
  {
    id: "south-hayward-parish",
    name: "South Hayward Parish (Food Pantry)",
    type: "food-bank",
    address: "27287 Patrick Avenue",
    city: "Hayward",
    state: "CA",
    zip: "94544",
    lat: 37.623,
    lng: -122.056,
    phone: "(510) 785-3663",
    email: "",
    hours: "Mon, Tue, Thu, Fri 1:00 PM – 4:00 PM (walk-up only)",
    description:
      "Partners with the Alameda County Community Food Bank to serve over 700 families per week with groceries in southern Hayward, and also operates an overnight shelter and resource center.",
    resources: [
      "Walk-up food pantry",
      "Hot lunch program (Mon–Fri 12:00 PM – 1:00 PM)",
      "Overnight emergency shelter",
      "Resource center referrals",
      "Hygiene supplies",
    ],
  },
  {
    id: "hope-4-the-heart",
    name: "Hope 4 The Heart",
    type: "food-bank",
    address: "22035 Meekland Avenue",
    city: "Hayward",
    state: "CA",
    zip: "94541",
    lat: 37.6287,
    lng: -122.0993,
    phone: "(510) 581-6473",
    email: "victoria@hope4theheart.org",
    hours:
      "Food Distribution: Tue 1:30 PM; 3rd Saturday of each month 7:00 AM",
    description:
      "An all-volunteer nonprofit food rescue and redistribution organization that feeds over 16,000 individuals each month, partnering with 50+ nonprofits to deliver food across the Bay Area.",
    resources: [
      "Food rescue",
      "Food redistribution to shelters/schools/pantries",
      "Mobile food distribution",
      "Affordable-housing food deliveries",
      "Senior housing deliveries",
    ],
  },
  {
    id: "svdp-alameda-county",
    name: "Society of St. Vincent de Paul of Alameda County",
    type: "food-bank",
    address: "2272 San Pablo Avenue",
    city: "Oakland",
    state: "CA",
    zip: "94612",
    lat: 37.8125,
    lng: -122.2747,
    phone: "(510) 638-7600",
    email: "",
    hours: "Office Mon–Fri; dining room and pantry open daily (call to confirm)",
    description:
      "Founded in 1938, this faith-based nonprofit operates the largest emergency shelter in Alameda County, a free dining room, food distribution, and workforce development programs serving unhoused and food-insecure residents.",
    resources: [
      "Free dining room (West Oakland campus)",
      "Food distribution",
      "Emergency shelter",
      "Clothing closet",
      "Workforce development",
      "Thrift stores (Fremont and Livermore)",
    ],
  },
  {
    id: "mandela-partners",
    name: "Mandela Partners",
    type: "harvest",
    address: "1344 7th Street",
    city: "Oakland",
    state: "CA",
    zip: "94607",
    lat: 37.808,
    lng: -122.293,
    phone: "(510) 433-0993",
    email: "info@mandelapartners.org",
    hours: "Office hours; CSA pickups and produce stand schedules vary",
    description:
      "A 501(c)(3) food justice nonprofit that partners with residents, family farmers, and community-based businesses to improve health, wealth, and food access in low-income West and East Oakland communities.",
    resources: [
      "Community produce stands",
      "CSA produce boxes (Mandela Produce Distribution)",
      "Healthy Retail Network (produce in corner stores)",
      "Culinary employment training",
      "Food business incubator (E14th Eatery + Kitchen)",
      "Wellness education",
    ],
  },
  {
    id: "st-marys-center",
    name: "St. Mary's Center",
    type: "food-bank",
    address: "925 Brockhurst Street",
    city: "Oakland",
    state: "CA",
    zip: "94608",
    lat: 37.823,
    lng: -122.2628,
    phone: "(510) 923-9600",
    email: "",
    hours: "Mon–Fri 9:30 AM – 1:00 PM; Sun 11:00 AM – 1:00 PM",
    description:
      "Founded in 1964 by the Sisters of Mercy, this West Oakland nonprofit serves low-income seniors and families with a food pantry, hot lunch program, case management, and senior housing.",
    resources: [
      "Food pantry",
      "Hot lunch program (Mon–Fri)",
      "Home-delivered meals for homebound seniors",
      "Case management and benefits enrollment",
      "Senior housing",
      "Transitional housing",
      "Preschool",
    ],
  },
  {
    id: "alameda-point-collaborative",
    name: "Alameda Point Collaborative",
    type: "harvest",
    address: "2550 Monarch Street, Building 2, Suites 8 & 9",
    city: "Alameda",
    state: "CA",
    zip: "94501",
    lat: 37.7701,
    lng: -122.3062,
    phone: "(510) 898-7800",
    email: "development@apcollaborative.org",
    hours: "Office Mon–Fri; on-site farm and nursery programs by appointment",
    description:
      "A supportive housing and services program on the former Alameda Naval Air Station that serves formerly homeless families and individuals through housing, an urban farm (Dig Deep Farms), a nursery, and a culinary social enterprise.",
    resources: [
      "Supportive housing",
      "Urban farm (Dig Deep Farms) and produce stand",
      "Ploughshares Nursery",
      "Culinary social enterprise kitchen",
      "Workforce development",
      "Children and youth programs",
      "Medical respite (Arnold's Place)",
    ],
  },
  {
    id: "salvation-army-hayward",
    name: "The Salvation Army Hayward Corps",
    type: "food-bank",
    address: "430 A Street",
    city: "Hayward",
    state: "CA",
    zip: "94541",
    lat: 37.6715,
    lng: -122.08,
    phone: "(510) 581-6444",
    email: "",
    hours:
      "Food Pantry: Tue & Thu 10:00 AM – 12:00 PM and 12:30 PM – 2:00 PM; Sack Lunch Mon–Fri 12:30 PM; Sunday Dinner 4:00 PM",
    description:
      "A faith-based community center serving Hayward, Castro Valley, San Leandro, and San Lorenzo with a food pantry, USDA commodity distribution, hot meals, and emergency assistance.",
    resources: [
      "Food pantry",
      "USDA commodity distribution",
      "Hot breakfast (Mon–Thu)",
      "Sack lunch (Mon–Fri)",
      "Sunday evening community dinner",
      "Worship and Bible study",
      "Disaster/PSPS response",
    ],
  },
];
